spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catchku?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
  #    username: application-secret 으로 따로 관리
  #    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true